spring:
  application:
    name: image-generation

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

gemini:
  api:
    key: ${GEMINI_API_KEY}
  model:
    image-generation: ${gemini.model.image-generation}
  retry:
    delay: ${gemini.retry.delay}

rate:
  limit:
    requests: 10
    duration: 1